# Generated by Django 5.1.2 on 2024-10-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedingtimetable',
            old_name='decsription',
            new_name='description',
        ),
    ]
