# Generated by Django 5.1.2 on 2024-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_feedingtimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
