# Generated by Django 5.1.2 on 2024-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedingtimetable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicksManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=255, unique=True)),
                ('number_of_chicks', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
