# Generated by Django 5.0.2 on 2024-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_phone_user_profile_img_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='user.jpg', upload_to=''),
        ),
    ]
